#!/bin/bash

# Script to add AFSC Strategic Objectives to DynamoDB using AWS CLI
# Run with: bash scripts/add-objectives.sh

# Set AWS credentials from shared.env.cjs
export AWS_REGION="us-east-1"
export AWS_ACCESS_KEY_ID="AKIATCKAO3PXX7TNQXXY"
export AWS_SECRET_ACCESS_KEY="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"

TABLE_NAME="captify-core-Objective"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Adding objectives to $TABLE_NAME..."

# Array of objectives
objectives=(
  '{"id":{"S":"obj-loe1-1"},"tenantId":{"S":"afsc"},"name":{"S":"Deliver On Time and On Cost"},"slug":{"S":"deliver-on-time-and-on-cost"},"app":{"S":"platform"},"ownerTeam":{"S":"Mission Operations"},"priority":{"S":"high"},"linkedOutcomes":{"L":[{"S":"outcome-loe1-1a"}]},"metrics":{"M":{"onTimeDelivery":{"M":{"target":{"N":"95"},"unit":{"S":"%"},"description":{"S":"Percent of depot and logistics operations delivered on or ahead of schedule"}}},"costVariance":{"M":{"target":{"N":"0"},"unit":{"S":"%"},"description":{"S":"Maintain zero cost overrun on production and sustainment"}}}}},"status":{"S":"active"},"description":{"S":"Ensure AFSC missions deliver aircraft, software, and logistics products on schedule and within cost targets."},"order":{"N":"1"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe1-2"},"tenantId":{"S":"afsc"},"name":{"S":"Exercise to Scale"},"slug":{"S":"exercise-to-scale"},"app":{"S":"platform"},"ownerTeam":{"S":"Mission Operations"},"priority":{"S":"medium"},"linkedOutcomes":{"L":[{"S":"outcome-loe1-2a"}]},"metrics":{"M":{"exerciseFrequency":{"M":{"target":{"N":"2"},"unit":{"S":"annual"},"description":{"S":"Number of scaled readiness exercises executed per year"}}},"responseTime":{"M":{"target":{"N":"10"},"unit":{"S":"hours"},"description":{"S":"Average time to deploy support in contested environments"}}}}},"status":{"S":"active"},"description":{"S":"Conduct enterprise-wide readiness and sustainment exercises to validate global operations and scaling capacity."},"order":{"N":"2"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe1-3"},"tenantId":{"S":"afsc"},"name":{"S":"Increase Depot Capability and Capacity to Support All Theaters (GENUS)"},"slug":{"S":"increase-depot-capability-genus"},"app":{"S":"platform"},"ownerTeam":{"S":"Industrial Base"},"priority":{"S":"critical"},"linkedOutcomes":{"L":[{"S":"outcome-loe1-3a"}]},"metrics":{"M":{"forwardNodes":{"M":{"target":{"N":"5"},"unit":{"S":"locations"},"description":{"S":"Number of forward sustainment nodes established under GENUS"}}},"depotThroughput":{"M":{"target":{"N":"15"},"unit":{"S":"%"},"description":{"S":"Percent increase in depot throughput capacity"}}}}},"status":{"S":"active"},"description":{"S":"Expand global sustainment reach through the Global Enterprise Network for Universal Sustainment (GENUS)."},"order":{"N":"3"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe2-1"},"tenantId":{"S":"afsc"},"name":{"S":"Develop an Enterprise Recruitment and Talent Management Strategy"},"slug":{"S":"develop-enterprise-recruitment-strategy"},"app":{"S":"platform"},"ownerTeam":{"S":"Human Capital"},"priority":{"S":"high"},"linkedOutcomes":{"L":[{"S":"outcome-loe2-1a"}]},"metrics":{"M":{"criticalSkillFills":{"M":{"target":{"N":"90"},"unit":{"S":"%"},"description":{"S":"Percent of critical-skill positions filled"}}},"candidatePoolGrowth":{"M":{"target":{"N":"25"},"unit":{"S":"%"},"description":{"S":"Growth in enterprise candidate pipeline"}}}}},"status":{"S":"active"},"description":{"S":"Build a unified recruitment and talent ecosystem to attract, hire, and retain world-class Airmen."},"order":{"N":"4"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe2-2"},"tenantId":{"S":"afsc"},"name":{"S":"Leverage Major Stakeholders to Improve and Streamline AFSC Hiring Processes"},"slug":{"S":"streamline-hiring-processes"},"app":{"S":"platform"},"ownerTeam":{"S":"Human Capital"},"priority":{"S":"medium"},"linkedOutcomes":{"L":[{"S":"outcome-loe2-2a"}]},"metrics":{"M":{"avgTimeToHire":{"M":{"target":{"N":"45"},"unit":{"S":"days"},"description":{"S":"Average number of days to complete hiring process"}}}}},"status":{"S":"active"},"description":{"S":"Partner across AFMC and AFPC to accelerate hiring and standardize workforce management practices."},"order":{"N":"5"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe2-3"},"tenantId":{"S":"afsc"},"name":{"S":"Innovate, Design, and Deliver Training for Next Generation Workforce"},"slug":{"S":"next-generation-training"},"app":{"S":"platform"},"ownerTeam":{"S":"Human Capital"},"priority":{"S":"critical"},"linkedOutcomes":{"L":[{"S":"outcome-loe2-3a"}]},"metrics":{"M":{"trainingCompletion":{"M":{"target":{"N":"90"},"unit":{"S":"%"},"description":{"S":"Percentage of employees completing new-gen digital training"}}},"digitalProficiencyIndex":{"M":{"target":{"N":"75"},"unit":{"S":"%"},"description":{"S":"Percent of workforce proficient in digital/AI tools"}}}}},"status":{"S":"active"},"description":{"S":"Develop and deploy competency-based training aligned to evolving digital sustainment needs."},"order":{"N":"6"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe2-4"},"tenantId":{"S":"afsc"},"name":{"S":"Develop a Comprehensive Employee Retention Plan"},"slug":{"S":"employee-retention-plan"},"app":{"S":"platform"},"ownerTeam":{"S":"Human Capital"},"priority":{"S":"medium"},"linkedOutcomes":{"L":[{"S":"outcome-loe2-4a"}]},"metrics":{"M":{"attritionRate":{"M":{"target":{"N":"8"},"unit":{"S":"%"},"description":{"S":"Target annual attrition rate"}}},"retentionIncentives":{"M":{"target":{"N":"200"},"unit":{"S":"count"},"description":{"S":"Number of retention incentive actions executed"}}}}},"status":{"S":"active"},"description":{"S":"Implement data-driven retention and workforce flexibility strategies to sustain a high-skill team."},"order":{"N":"7"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe2-5"},"tenantId":{"S":"afsc"},"name":{"S":"Optimize In-Person Work"},"slug":{"S":"optimize-in-person-work"},"app":{"S":"platform"},"ownerTeam":{"S":"Human Capital"},"priority":{"S":"low"},"linkedOutcomes":{"L":[{"S":"outcome-loe2-5a"}]},"metrics":{"M":{"onSiteEffectiveness":{"M":{"target":{"N":"90"},"unit":{"S":"%"},"description":{"S":"Employee satisfaction with hybrid/in-person model"}}}}},"status":{"S":"active"},"description":{"S":"Define hybrid work standards and collaboration metrics to balance mission performance and flexibility."},"order":{"N":"8"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe3-1"},"tenantId":{"S":"afsc"},"name":{"S":"Increase Inventory"},"slug":{"S":"increase-inventory"},"app":{"S":"platform"},"ownerTeam":{"S":"Supply Chain"},"priority":{"S":"critical"},"linkedOutcomes":{"L":[{"S":"outcome-loe3-1a"}]},"metrics":{"M":{"inventoryFillRate":{"M":{"target":{"N":"95"},"unit":{"S":"%"},"description":{"S":"Percent of critical inventory positions filled"}}},"stockoutRate":{"M":{"target":{"N":"2"},"unit":{"S":"%"},"description":{"S":"Percent of stockouts reduced"}}}}},"status":{"S":"active"},"description":{"S":"Increase available inventory and accuracy to improve readiness while balancing cost efficiency."},"order":{"N":"9"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe3-2"},"tenantId":{"S":"afsc"},"name":{"S":"Streamline Acquisition Processes and Expand Buying Power"},"slug":{"S":"streamline-acquisition-processes"},"app":{"S":"platform"},"ownerTeam":{"S":"Supply Chain"},"priority":{"S":"high"},"linkedOutcomes":{"L":[{"S":"outcome-loe3-2a"}]},"metrics":{"M":{"procurementCycleTime":{"M":{"target":{"N":"15"},"unit":{"S":"%"},"description":{"S":"Reduction in average procurement cycle time"}}}}},"status":{"S":"active"},"description":{"S":"Simplify and standardize acquisition workflows to accelerate part procurement and contracting."},"order":{"N":"10"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe3-3"},"tenantId":{"S":"afsc"},"name":{"S":"Expand the Commercial and Organic Supplier Base"},"slug":{"S":"expand-supplier-base"},"app":{"S":"platform"},"ownerTeam":{"S":"Supply Chain"},"priority":{"S":"high"},"linkedOutcomes":{"L":[{"S":"outcome-loe3-3a"}]},"metrics":{"M":{"supplierGrowth":{"M":{"target":{"N":"20"},"unit":{"S":"%"},"description":{"S":"Increase in active suppliers"}}},"smallBusinessParticipation":{"M":{"target":{"N":"25"},"unit":{"S":"%"},"description":{"S":"Percent of spend with small business suppliers"}}}}},"status":{"S":"active"},"description":{"S":"Diversify supplier ecosystem to reduce dependency and increase supply resilience."},"order":{"N":"11"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe3-4"},"tenantId":{"S":"afsc"},"name":{"S":"Repair Network Management Optimization"},"slug":{"S":"repair-network-optimization"},"app":{"S":"platform"},"ownerTeam":{"S":"Supply Chain"},"priority":{"S":"critical"},"linkedOutcomes":{"L":[{"S":"outcome-loe3-4a"}]},"metrics":{"M":{"repairCycleTime":{"M":{"target":{"N":"20"},"unit":{"S":"%"},"description":{"S":"Reduction in average repair cycle time"}}},"utilizationRate":{"M":{"target":{"N":"85"},"unit":{"S":"%"},"description":{"S":"Network utilization efficiency"}}}}},"status":{"S":"active"},"description":{"S":"Integrate predictive analytics into repair network management for efficiency and readiness gains."},"order":{"N":"12"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe3-5"},"tenantId":{"S":"afsc"},"name":{"S":"Implement FY22 NDAA Section 142"},"slug":{"S":"implement-ndaa-section-142"},"app":{"S":"platform"},"ownerTeam":{"S":"Supply Chain Risk Management"},"priority":{"S":"high"},"linkedOutcomes":{"L":[{"S":"outcome-loe3-5a"}]},"metrics":{"M":{"complianceScore":{"M":{"target":{"N":"100"},"unit":{"S":"%"},"description":{"S":"Percent compliance with NDAA Section 142"}}}}},"status":{"S":"active"},"description":{"S":"Embed SCRM standards and transparency into acquisition and supplier oversight processes."},"order":{"N":"13"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe4-1"},"tenantId":{"S":"afsc"},"name":{"S":"Develop Integrated and Aligned OIB Investment Optimization Plan"},"slug":{"S":"oib-investment-optimization"},"app":{"S":"platform"},"ownerTeam":{"S":"Industrial Base"},"priority":{"S":"critical"},"linkedOutcomes":{"L":[{"S":"outcome-loe4-1a"}]},"metrics":{"M":{"capitalInvestment":{"M":{"target":{"N":"8"},"unit":{"S":"%"},"description":{"S":"Annual reinvestment in depot modernization (as % of revenue)"}}}}},"status":{"S":"active"},"description":{"S":"Develop an enterprise-wide Organic Industrial Base investment plan to optimize infrastructure and capabilities."},"order":{"N":"14"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe4-2"},"tenantId":{"S":"afsc"},"name":{"S":"Develop and Deploy a Scalable and Secure AFSC Digital Ecosystem"},"slug":{"S":"develop-digital-ecosystem"},"app":{"S":"platform"},"ownerTeam":{"S":"Industrial Base / IT"},"priority":{"S":"critical"},"linkedOutcomes":{"L":[{"S":"outcome-loe4-2a"}]},"metrics":{"M":{"digitalIntegrationScore":{"M":{"target":{"N":"90"},"unit":{"S":"%"},"description":{"S":"Percent of systems integrated into digital ecosystem"}}}}},"status":{"S":"active"},"description":{"S":"Digitally connect depots, supply chains, and software directorates into a unified, secure digital ecosystem."},"order":{"N":"15"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
  '{"id":{"S":"obj-loe4-3"},"tenantId":{"S":"afsc"},"name":{"S":"Deploy MRO/MRO-S"},"slug":{"S":"deploy-mro-mros"},"app":{"S":"platform"},"ownerTeam":{"S":"Industrial Base / IT"},"priority":{"S":"high"},"linkedOutcomes":{"L":[{"S":"outcome-loe4-3a"}]},"metrics":{"M":{"systemUptime":{"M":{"target":{"N":"99.9"},"unit":{"S":"%"},"description":{"S":"System uptime for MRO/MRO-S platform"}}},"userAdoption":{"M":{"target":{"N":"85"},"unit":{"S":"%"},"description":{"S":"Percent of functional users onboarded"}}}}},"status":{"S":"active"},"description":{"S":"Deploy modernized Maintenance, Repair, and Overhaul (MRO/MRO-S) systems to standardize execution and enable digital sustainment."},"order":{"N":"16"},"createdAt":{"S":"'"$TIMESTAMP"'"},"updatedAt":{"S":"'"$TIMESTAMP"'"},"createdBy":{"S":"system"},"updatedBy":{"S":"system"}}'
)

SUCCESS_COUNT=0
FAILURE_COUNT=0

# Loop through and insert each objective
for item in "${objectives[@]}"; do
  aws dynamodb put-item \
    --table-name "$TABLE_NAME" \
    --item "$item" \
    2>&1

  if [ $? -eq 0 ]; then
    ((SUCCESS_COUNT++))
    echo "✓ Added objective"
  else
    ((FAILURE_COUNT++))
    echo "✗ Failed to add objective"
  fi
done

echo ""
echo "Complete: $SUCCESS_COUNT succeeded, $FAILURE_COUNT failed"
